### ISSUE TITLE
color code dov

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#109]
Would it be possible to share the color scheme that is used by DOV in the Virtual borehole? Or where to find it?

**Comment by Roel** [comment]
I made a Gist with the TypeScript files containing the information from the Virtual borehole: https://gist.github.com/Roel/b99f3672ea3c845a76e92fd3a0de19e4

Together with the two WMS layers for both models and the elevation service for DHMV2, this should be all you need.

**Comment by pjhaest** [comment]
Ok, thanks!
