### ISSUE TITLE
Invalid token in xml results in crash of application

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#110]
I get an invalid token error on line 27 of
 'https://www.dov.vlaanderen.be/data/interpretatie/1987-070909.xml'

maybe it's good to include a catch for such errors with an error logging, because currently it crashes the application on line 160 of util/caching.py ?

**Comment by Roel** [comment]
I created a ticket (XDOVCL-870) in the DOV tracking system for the first issue.
