### ISSUE TITLE
pydov logo

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#116]
Presenting pydov I thought it would be nice to add a logo. 
For example:
![pydov_icon](https://user-images.githubusercontent.com/22764347/47999374-bbb22a80-e102-11e8-8ed7-202a80b849ae.png)

**Comment by stijnvanhoey** [comment]
@pjhaest good idea; do you have an `svg`-version?

**Comment by pjhaest** [comment]
I have one, but github does not seem to support svg in issues (unless zipped?). I'll send it by mail.

**Comment by Roel** [comment]
Good idea! You can always create a branch and commit it, SVG is just XML after all.

**Comment by peterdesmet** [comment]
As discussed in https://github.com/DOV-Vlaanderen/pydov/pull/117#issuecomment-436188298, here's my version for a pydov logo:

![pydov 2](https://user-images.githubusercontent.com/600993/48427168-77f59b80-e768-11e8-9fdc-c52c068de962.png)

Uses:

- Hex format
- Flanders sans serif font
- Flanders yellow
- Icon for "boring" (thanks @Roel)
- png (sorry, I'm not skilled in creating svg logos. 😬I also don't think an svg logo is really necessary here)

If I get some 👍I can see how to properly add it to the repo. For reference, here's the 300dpi version:

![pydov](https://user-images.githubusercontent.com/600993/48426983-1d5c3f80-e768-11e8-85b3-19b2ddbcd8a4.png)

**Comment by pjhaest** [comment]
Ok, nice. One question: do we use 'pydov', or 'PyDOV' for the package? Do you think it's better to use the notation of the package name in the logo, or not? I like simple, so pydov is ok.

**Comment by stijnvanhoey** [comment]
We discussed it today and checked the [pep8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) section:

> Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

So, we came to the conclusion of using `pydov` as package name. I'll adapt the title etc in the documentation, see #118

**Comment by Roel** [comment]
I think this can be closed, since merging #119 ?

**Comment by peterdesmet** [comment]
Yes.
