### ISSUE TITLE
Add support for water samples (water quality observations)

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#126]
Currently, the DOV services returns _by default_ no `grondmonsters` (`subsoil sample`) as part of the `Boring` XML, whereas it actually provides the `watermonsters` (`water sample`) as part of the groundwater screens water heads.

We (_during January sprint_) propose to make this consistent and also exclude the water sample observations from the water heads XML. As such, using pydov to query groundwater screens would focus on heads only and not incorporate observations from water samples. Moreover, we can create for the pydov user separate entry points to query water and subsoil samples:
* `subsoil sample`: the WFS service is existing, so similar setup to other data types is possible
* `water sample`: a new WFS service need to be defined in order to provide a pydov service similar to the other data types

**Comment by Roel** [comment]
Observations are now no longer included in the filters/heads XML.
Water sample WFS service still to do.
