### ISSUE TITLE
Overview data types supported by pydov

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#128]
| Data type | implemented | tutorial written  | Remarks | 
| -------------|--------------------|---------------------|--------------|
| Informele stratigrafie | x | x  |  |
| Formele stratigrafie | x  | x  |  |
| Lithologische beschrijvingen | x | x  |  |
| Gecodeerde lithologie | x |   |  |
| Hydrogeologische stratigrafie | x | x  |  |
| Informele hydrogeologische stratigrafie | x  | x  |   |
| Quartaire stratigrafie | x  | x  |   | 
| Geotechnische coderingen |  x | x  |  | 
| Boreholes (In Dutch: boring) | x | x |   |
| CPT data (In Dutch: sonderingen) | x  | x  |   | 
| Groundwater screen (In Dutch: Grondwaterfilter) | x | x | required some examples on time series  |
| Water sample | x  | x  |  |
| Subsoil sample | x  |  x  |  |

**Comment by stijnvanhoey** [comment]
@pjhaest and @Roel as discussed, the main goal for the next sprint in May 2019 is to support also the missing data types.

**Comment by pjhaest** [comment]
just updated quartaire stratigrafie, next one is for code sprint

**Comment by pjhaest** [comment]
all data types included and documented
