### ISSUE TITLE
Query attribute `gemeente` issue

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#130]
The examples/tutorials are using `gemeente` attribute a lot. However, the reference to `gemeente` (municipality) is not a spatial link, but originates from the user form (*not required*) and provided by the user when submitting the data. Hence, the quality/accuracy of the field is limited and not considering changing boundaries or aggregations of municipalities. 

As such, the query attribute `gemeente` should be used with caution! As pydov is just relying on DOV for the provision of this field, we should document this to the user.

**Comment by stijnvanhoey** [comment]
While informing the user, we could use a chain with other services (e.g. `informatie vlaanderen`): 1/ request GML for given municipality from their service 2/ use this GML as input for the search with pydov

**Comment by Roel** [comment]
I started a new notebook for examples like this one: see the `remote-wfs-gml-example` branch. Needs to be extended with more documentation off course.

I'm planning to add more examples using other services when I find some time :)
