### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#148]
It's time to get our first release out of the door :)

Once all other issues in the v0.1.0 are done, we can proceed with the release.

Meanwhile we can start by documenting the process here?

**Comment by pjhaest** [comment]
:+1

**Comment by pjhaest** [comment]
maybe also consider a good reference for pydov? @stijnvanhoey I think you have experience with JOSS? Or would you just leave it like that until a research paper is finished (thinking of one, but looking for time to write)
