### ISSUE TITLE
Groundwater permits in pydov

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#153]
A suggestion: should we add the groundwater permits as a type to pydov? It's a dataset that can be accessed with the 'Verkenner'.  It's only a wfs layer. The largest benefit would be the extended spatial queries that are now possible on the wfs.
For the moment we have a separate script at AGT using the pydov in the back, but it would be cleaner if it's included in the pydov search?

**Comment by Roel** [comment]
The groundwater permits services are about to change in the near(ish) future, after the new groundwater permits application is released to production. There is no XML export service planned for the permits at this moment, so it will be WFS only (as it is now).

We can integrate them as a type in pydov for consistency, but in fact this is a WFS service like any other.

In any case I suggest waiting for the updated services that will be available after the production release of the new applications.

**Comment by pjhaest** [comment]
Indeed, wfs only, but with extended search in comparison to standard owslib (thx Roel)
Ok, will discuss this in the next code sprint, or after release

**Comment by Roel** [comment]
My idea would be to contribute the (spatial) WFS quering to owslib, so it can be used by anyone for any WFS service.

**Comment by Roel** [comment]
Which wouldn't stop you from using pydov's extended WFS querying on other layers (or other WFS 1.1.0 services):

```python
from pydov.util import owsutil
from pydov.util.location import (
    WithinDistance,
    Point,
)

from owslib.etree import etree

wfs_service = 'https://www.dov.vlaanderen.be/geoserver/wfs'
wfs_type = 'gw_vergunningen:huidige_verg'

location = WithinDistance(Point(150000, 150000), 15, 'km')

schema = owsutil.get_remote_schema(wfs_service, wfs_type)

feature_request = owsutil.wfs_build_getfeature_request(
    typename=wfs_type,
    geometry_column=schema['geometry_column'],
    location=location)

result = owsutil.wfs_get_feature(wfs_service, feature_request)

resulttree = etree.fromstring(result)
```

You will need to parse the resulting XML tree containing the features yourself, though.

**Comment by pjhaest** [comment]
:+1:
