### ISSUE TITLE
Empty subtype fields limit records of main type (inner join)

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#162]
The current implementation of types and subtypes is one where a dataframe record is returned when both are not-null (can be thought of as an inner join).

This means that, when you request a field from a subtype, a record is only returned in the dataframe when this field is not-null (even if the other fields of the main type are not-null). This is contrary to fields of the main type itself: they are included as NaN in the dataframe when they are null.

This has some consequences that might not be immediately obvious to the user, especially taking our default dataframe fields into account.

For example: by default, since there are fields of the Peilmeting subtype in the dataframe of Grondwaterfilters, you only will get Filters with at least one Peilmeting:

```
fs = GrondwaterFilterSearch()

df_filters = fs.search(
    query=And([
        Not([PropertyIsNull(propertyname='pkey_filter')]),
        PropertyIsNull(propertyname='peilmetingen_tot')
    ]),
    location=WithinDistance(Point(139417, 220199), 5000, 'm'))
> [000/010] cccccccccc

print(df_filters)
> Empty DataFrame
```

To get the data of the filters, you have to exclude the fields from the Peilmeting subtype:
```
fs = GrondwaterFilterSearch()

df_filters = fs.search(
    query=And([
        Not([PropertyIsNull(propertyname='pkey_filter')]),
        PropertyIsNull(propertyname='peilmetingen_tot')
    ]),
    location=WithinDistance(Point(139417, 220199), 5000, 'm'),
    return_fields=('pkey_filter', 'pkey_grondwaterlocatie', 'gw_id',
                   'filternummer', 'filtertype', 'x', 'y', 'mv_mtaw',
                   'gemeente', 'meetnet_code', 'aquifer_code',
                   'grondwaterlichaam_code', 'regime',
                   'diepte_onderkant_filter', 'lengte_filter'))
> [000/010] cccccccccc

print(df_filters)
>                                          pkey_filter  \
> 0  https://www.dov.vlaanderen.be/data/filter/2007...   
> 1  https://www.dov.vlaanderen.be/data/filter/2007...   
> 2  https://www.dov.vlaanderen.be/data/filter/2007...   
```

The same holds for the other types: Boring without Boormethode, Interpretation without Laag, Sondering without Meetdata, ...

I think it will make more sense to align with the WFS fields and fields from the main XML type and change this behaviour to a 'left join' instead (i.e. setting the fields of the subtype to Nan instead of removing the record)?

**Comment by pjhaest** [comment]
Ok, it makes sense to return NaNs for empty subtypes if you query them. Does this also relate to #161, where you query for the NaNs?

**Comment by Roel** [comment]
No, that is unrelated. That is to exclude things that are not Filters from the results of Grondwaterfilter.
