### ISSUE TITLE
DOI badge links to old 0.1.3 release

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#180]
The DOI badges in the README and the docs link to the first release on Zenodo, i.e. 0.1.3. It would be better to link to the most recent stable release.

The following link and badge will always resolve to the most recent stable version:
* https://doi.org/10.5281/zenodo.2788680
* https://zenodo.org/badge/DOI/10.5281/zenodo.2788680.svg

**Comment by pjhaest** [comment]
👍
