### ISSUE TITLE
Make order of dataframe columns match the return_fields order

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#192]
Current implementation is that the order of the output dataframe columns follows the order of the fields defined in the object type. I'm not exactly sure as to why we have opted for this, but we have explicitly implementated it this way (there is even [a test](https://github.com/DOV-Vlaanderen/pydov/blob/685fa4ad44ed9ffb1e6f6cd0f44dd7beb8af5815/tests/abstract.py#L401-L421) to check this behaviour).

When using the `return_fields` parameter in a search, this can have as a consequence that the order of the columns in the output dataframe is different from the order provided in return_fields.

Would it make more sense to use the return_fields order in the output dataframe? Mind that currently return_fields can have no order defined (as it can be a set, for instance).

**Comment by pjhaest** [comment]
I think the order of the columns in the dataframe should not be fixed, since reference is mostly made by the column name (or should be anyway). So yes, it can be in the order of the `return_fields` parameter, with the default as before?
