### ISSUE TITLE
Promote 0.3.0 to 'beta'

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#193]
I believe us to be beyond '[Development Status :: 2 - Pre-Alpha](https://github.com/DOV-Vlaanderen/pydov/blob/685fa4ad44ed9ffb1e6f6cd0f44dd7beb8af5815/setup.py#L42)' by now, so I suggest release 0.3.0 to be promoted to 'Development Status :: 4 - Beta'.

As soon as all available DOV types are implemented, a stable 1.0.0 can be released - preferably before the end of the year.

**Comment by pjhaest** [comment]
will work on the samples in the next code sprint
