### ISSUE TITLE
dates in results are not pd.Datetime format

### ISSUE THREAD

**Issue by johanvdw** [DOV-Vlaanderen/pydov#200]
See eg: https://pydov.readthedocs.io/en/latest/notebooks/search_grondwaterfilters.html#Working-with-water-head-time-series

We still convert using pd.to_datetime . I think this should be done when we create the dataframe.
We should probably also have a look at the other datatypes as well.

**Comment by stijnvanhoey** [comment]
Good point, would be good to be explicit about the data types users can expect.

**Comment by Roel** [comment]
I think we might have (not) done this on purpose: date and time are two seperate columns in our dataframe (where date is notnull and time isn't). I think we didn't want to convert the date to a timestamp ourselves to let the user decide whether to use the date only (with a time of 00:00), or the date + time combined.

**Comment by stijnvanhoey** [comment]
ok, makes sense. We also document it in the [tutorials  ](https://pydov.readthedocs.io/en/stable/notebooks/search_grondwaterfilters.html#Working-with-water-head-time-series)so maybe that would be enoug?
