### ISSUE TITLE
Add pydov to pyopensci initiative?

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#213]
According to the described [scope](https://www.pyopensci.org/dev_guide/peer_review/aims_scope.html), the pydov package seems to fit...

> Data retrieval: Packages for accessing and downloading data from online sources. Includes wrappers for accessing APIs.

We could consider to add pydov to pyopensci. I checked and - in contrast to ropensci - there is no transmission of ownership to a  central pyopenci github organisation:

> Authors of contributed packages essentially maintain the same ownership they had prior to their package joining the pyOpenSci suite.

Howto is described in the [pyopensci guide](https://www.pyopensci.org/dev_guide/packaging/packaging_guide.html)

**Comment by stijnvanhoey** [comment]
see https://github.com/pyOpenSci/software-review/issues/19, done!

**Comment by Roel** [comment]
@stijnvanhoey Will you make the PR to include pydov to pyopensci.github.io or shall I? The task has been checked [here](https://github.com/pyOpenSci/software-review/issues/19#issuecomment-717995868) but I don't see any PR?
