### ISSUE TITLE
Python2 support dropped in OWSLib >= 0.19.0

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#215]
OWSLib 0.19.0 (released last week) dropped support for Python2. Since we don't pin versions in the requirements file, pydov's Travis is failing on Python2 now.

I'd propose to pin OWSLib in the requirements to version <= 0.18.0 and release a final 1.0.0 of pydov which is still Python2 compatible.

Early next year we can work on dropping Python2 support in pydov too and release this as 2.0.0.

**Comment by pjhaest** [comment]
👍
