### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#245]
when do we tend to create a new stable version? Just to make sure the changes from the last sprint are visible in the default readthedocs (stable).

**Comment by Roel** [comment]
I don't think the changes in master currently justify a 2.0.0 release, so I was not planning to release anytime soon. IMO the documentation should follow the code changes and releases, not the other way around?

**Comment by pjhaest** [comment]
You are right of course, I just added this because I saw that our changes to the rst files are not yet reflected on ReadTheDocs?

**Comment by Roel** [comment]
They should be on the master version: https://pydov.readthedocs.io/en/latest/

**Comment by pjhaest** [comment]
indeed, but if you follow the readthedocs link on the main page, you get the 'stable' version. Should this be changed to 'latest'?

**Comment by Roel** [comment]
You mean on the main page of the Github repo? I changed that one to go to the latest (makes sense since it reflects Github's master branch).

For the other links (in the Readme and the DOV website, f.ex.) I still think it makes more sense to link to the latest stable as this is what most people shall be running/installing?

**Comment by pjhaest** [comment]
👍

**Comment by Roel** [comment]
Without accidents or objections, I plan on releasing pydov 2.0.0 this Sunday, 26th of July. Mainly to get the fix for #285 out of the door, but also to release the work of our last two codesprints. :crossed_fingers:

**Comment by Roel** [comment]
pydov 2.0.0 has been released :fireworks:
