### ISSUE TITLE
osgeo4w compatibility

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#25]
As a subset of the target audience will be installing Python and GIS tools with `osgeo4w`, it is good to take this into account:
* [ ] add CI tests in the osgeo4w context.
* [ ] document the installation for this target audience

**Comment by pjhaest** [comment]
could be closed, not our intention to test for all potential compatibility issues

**Comment by stijnvanhoey** [comment]
ok, closing.
