### ISSUE TITLE
Add 'kleur' to boreholes

### ISSUE THREAD

**Issue by ChandraAlgoe** [DOV-Vlaanderen/pydov#252]
* PyDOV version:v1.0.0
* Python version:3.7
* Operating System:Windows 10 Enterprise 1803

### Description

In the xml of a borehole, there is information in the section 'details'. From this section only 'boormethode' is available in pydov. Can the additional data be made available in pydov? It concerns 'consistentie', 'vochtgehalte' and 'kleur'. 

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Roel** [comment]
Hi Chandra,

The default subtype of the Boring datatype is indeed the 'Boormethode'. However, you change this yourself thanks to pydov's [object type customisation](https://pydov.readthedocs.io/en/stable/output_fields.html#defining-custom-object-types).

Your use case implies defining a new subtype 'Kleur' (or similar for 'Consistentie' and 'Vochtgehalte') and registering it in a custom Boring type. This would be similar to adding 'Technieken' to the Sondering type as described [here](https://pydov.readthedocs.io/en/stable/output_fields.html#adding-a-new-subtype-to-a-main-type).

I will prepare a pull request to add the 'Kleur' example to the documentation. It will be along the lines of:

```python
from pydov.types.abstract import AbstractDovSubType
from pydov.types.boring import Boring
from pydov.search.boring import BoringSearch
from owslib.fes import PropertyIsEqualTo

class Kleur(AbstractDovSubType):
    
    rootpath = './/boring/details/kleur'

    fields = [
        XmlField(name='diepte_kleur_van',
                 source_xpath='/van',
                 definition='Bovenkant van de laag met een bepaalde bekisting, in meter.',
                 datatype='float'),
        XmlField(name='diepte_kleur_tot',
                 source_xpath='/tot',
                 definition='Onderkant van de laag met een bepaalde bekisting, in meter.',
                 datatype='float'),
        XmlField(name='kleur',
                 source_xpath='/kleur',
                 definition='Grondkleur voor het diepte-interval',
                 datatype='string')
    ]


class BoringKleur(Boring):
    subtypes = [Kleur]

bs = BoringSearch(objecttype=BoringKleur)

df = bs.search(
    query=PropertyIsEqualTo('pkey_boring', 'https://www.dov.vlaanderen.be/data/boring/2004-103984')
)
df.head()
```

You can do the same for 'Consistentie' and 'Vochtgehalte'.

If the 'demand' for this information is high enough, we can consider adding these subtypes to pydov core as well.

Take care!

**Comment by ChandraAlgoe** [comment]
Dear Roel,

Thank you for your help!  For the moment it is not necessary to add these subtypes to pydov core. I forwarded your answer to Roel de Koninck, He was aware that is was already possible, but we needed some guidance!

Take Care!

**Comment by Roel** [comment]
The example has been added in the [documentation](https://pydov.readthedocs.io/en/latest/notebooks/customizing_object_types.html#Adding-color-to-the-Borehole-dataframe).

I'm going to close the issue, but don't hesitate to reopen it or create a new issue should any questions remain!
