### ISSUE TITLE
field grondsoort_bggg contains symbols when i.e. á occurs

### ISSUE THREAD

**Issue by ChandraAlgoe** [DOV-Vlaanderen/pydov#266]
* PyDOV version: 1.0.0
* Python version: 3.7
* Operating System: Windows 10 

### Description

I want a list of 'grondmonsters' from boringen containing 'GEO-18'. I derived the list. In the output the á is replaced by something like A, see for example line 70 in out2.txt (attached)
[out2.txt](https://github.com/DOV-Vlaanderen/pydov/files/4650310/out2.txt)

### What I Did

```
import pydov

from pydov.search.grondmonster import GrondmonsterSearch
grondmonster = GrondmonsterSearch()

print(grondmonster.get_description())

fields = grondmonster.get_fields()
# print available fields
for f in fields.values():
    print(f['name'])

fields['grondsoort_bggg']

from owslib.fes import PropertyIsLike
from pydov.util.location import Within, Box


query = PropertyIsLike(propertyname='boornummer',
                          literal='%GEO-18%')
df = grondmonster.search(query=query,return_fields=
                         ('naam','boornummer','diepte_van_m','diepte_tot_m',
                          'grondsoort_bggg')

#Schrijf weg naar out.csv
df.to_csv('out2.csv', index=False)
```
see for example line 70 in out2.txt

**Comment by Roel** [comment]
Hey Chandra,

Your example CSV and the code you shared both give a good result here on my pc:
![image](https://user-images.githubusercontent.com/140299/82363341-f5f5cb00-9a0d-11ea-9031-0297e1c47502.png)

Which program are you using to open the CSV? Does it look all right if you open it in Notepad++?

**Comment by ChandraAlgoe** [comment]
Dear Roel,

In Notepad++ the symbol is OK.
I see this when I open the csv in Excel:

![image](https://user-images.githubusercontent.com/48786550/82416331-207d6d80-9a7a-11ea-9126-b9646ecc5400.png)

**Comment by johanvdw** [comment]
Chandra,

You can solve this by opening a blank excel workbook and from the data tab choosing from text/csv:
![image](https://user-images.githubusercontent.com/868434/83124476-2bfe1380-a0ce-11ea-8494-bfb7cc5c07bd.png)

Next select your file and in the next dialog choose 65001: Unicode as the 'File origin'
![image](https://user-images.githubusercontent.com/868434/83124694-71224580-a0ce-11ea-9652-b401dcd594a0.png)

As this procedure is quite cumbersome, you could also try to write excel files directly from your tables:

`df.to_excel('out2.xlsx')`

**Comment by Roel** [comment]
I'm going to close this issue since I believe this is solved? Don't hesitate to reopen if it is not the case or open a new issue if you have further questions!
