### ISSUE TITLE
Missing values in XML export

### ISSUE THREAD

**Issue by johanvdw** [DOV-Vlaanderen/pydov#27]
It looks like some values are missing in XML export, but are present in the UI.

Listing those here so we can pass them (grouped) to the DOV development team.

grondwater observaties: detectie

**Comment by Roel** [comment]
This seems to be fixed in the meantime, detectieconditie is available in the XML.

For example:
https://www.dov.vlaanderen.be/data/watermonster/2006-009272
https://www.dov.vlaanderen.be/data/watermonster/2006-009272.xml

**Comment by johanvdw** [comment]
We actually use this in import as well.
