### ISSUE TITLE
Switch to layer level WFS endpoints

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#281]
Since the main DOV WFS endpoint has grown to ~ 2400 feature types (and 5+ MB unzipped) and we're using only ~ 15 of them in pydov, we might benefit to switch to the layer level endpoints instead. 

Next to reduce load on the Geoserver, this will likely speed up pydov "cold start" and might reduce timeout issues in CI environments (#279).

**Comment by Roel** [comment]
I looked into this today, but I'm a little puzzled by my preliminary results.

I made a tiny example with a BoringSearch instance and a single query retrieving a single (cached) result, as this only measures WFS and metadata setup:
```python
from pydov.search.boring import BoringSearch

bs = BoringSearch()
df = bs.search(max_features=1)
```

Then I tried three different WFS endpoints for the Boringen layer to see difference in performance:

First I tried the service-level WFS endpoint containing all feature types (this is the one we are using at this moment):
```
https://www.dov.vlaanderen.be/geoserver/wfs
            Mean        Std.Dev.    Min         Median      Max
real        3.065       1.190       2.229       2.674       7.917       
user        1.618       0.035       1.555       1.613       1.697       
sys         0.696       0.031       0.620       0.703       0.751
```

Next up, I switched to the layer level endpoint containing only the Boringen feature type we need. While I expected this to be a lot faster (since it is much smaller), surprisingly it is about 3x slower!
```
https://www.dov.vlaanderen.be/geoserver/dov-pub/Boringen/wfs
            Mean        Std.Dev.    Min         Median      Max
real        8.738       1.345       6.614       8.648       12.937      
user        0.916       0.034       0.860       0.908       0.982       
sys         0.650       0.044       0.522       0.653       0.724
```

The last endpoint to try is the workspace-wide endpoint containing all feature types in the same workspace as the Boringen layer. This seems to be the fastest: almost twice as fast as the original endpoint and a lot faster than the layer-level endpoint.
```
https://www.dov.vlaanderen.be/geoserver/dov-pub/wfs
            Mean        Std.Dev.    Min         Median      Max
real        1.499       0.087       1.269       1.504       1.669       
user        0.953       0.039       0.875       0.956       1.021       
sys         0.664       0.043       0.578       0.669       0.738
```

I'm a bit puzzled why the layer-level endpoint is so slow when compared to the original endpoint.. I thought maybe the main WFS endpoint is used more frequently so it it more likely to be cached somewhere (reverse proxy?). Remains the fact that the workspace-level endpoint is the fastest (maybe this is the best tradeoff between usage frequency (caching) and size?).

The conclusion from these (limited) experiments is that it might be better to use the workspace-level endpoints instead of the layer-level endpoints, althought I'd like to understand why.

**Comment by NielsCharlier** [comment]
The explanation is that
1) endpoints are a very different concept from request parameters.
2) particularities in geoserver's internal API's and implementations that are often written without JDBCConfig's use of database access in mind

When we make a request for a particular layer via the request parameters, the service implementation asks the catalog for that layer, plain and simple. The jdbc implementation of the catalog than queries the database for that layer.

A workspace/layer endpoint provides a kind of filtered version of an entire geoserver. That means a filter is placed on top of the catalog, that will applied every time anything in geoserver asks information from the catalog. For example, a service may ask the catalog to query *all* layers, then the filter will go through each of those layers and apply the filter on each of them. In the case of jdbcconfig, this means many more database requests and more much more data transfer.

Ideally, this could be optimised. Not so easy in practice because it would require a lot of core changes that are mainly useful for jdbcconfig, a community module that isn't used so often unfortunately.

Hope that clarifies it.

**Comment by pjhaest** [comment]
Thx for the explanation. Not sure I get the complete picture, but it seems related to things out of our scope.

**Comment by Roel** [comment]
Hi Niels!

Thanks for the explanation. If I understand correctly the main endpoint is faster to calculate server-side than the other 'virtual' endpoints due to the added (expensive) filtering?

If that filtering is the same for both the workspace and the layer-level endpoint, I don't yet understand why the former is actually faster than the main endpoint?

I did some further testing to distinguish between server-side 'rendering' and document download time (size related). I did this by issuing HEAD requests to eliminate the data transfer and only measure the server time:

```
1: curl --head --header "Cache-Control: no-cache, max-age=0" https://www.dov.vlaanderen.be/geoserver/wfs?version=1.1.0&request=GetCapabilities
            Mean        Std.Dev.    Min         Median      Max
real        0.391       0.088       0.316       0.349       0.614       
user        0.024       0.009       0.008       0.023       0.044       
sys         0.009       0.005       0.000       0.009       0.023

1: curl --head --header "Cache-Control: no-cache, max-age=0" https://www.dov.vlaanderen.be/geoserver/dov-pub/wfs?version=1.1.0&request=GetCapabilities
            Mean        Std.Dev.    Min         Median      Max
real        0.286       0.064       0.226       0.261       0.478       
user        0.020       0.007       0.008       0.019       0.032       
sys         0.008       0.005       0.000       0.008       0.020

: curl --head --header "Cache-Control: no-cache, max-age=0" https://www.dov.vlaanderen.be/geoserver/dov-pub/Boringen/wfs?version=1.1.0&request=GetCapabilities
            Mean        Std.Dev.    Min         Median      Max
real        3.742       0.543       2.525       3.877       4.367       
user        0.031       0.012       0.010       0.034       0.046       
sys         0.010       0.006       0.000       0.009       0.023
```

As you can see, the workspace-level endpoint is as fast or faster than the main endpoint; the layer-level endpoint being a lot slower.

If you do the full GET request including download of the response, things change a little bit, resulting more or less in the results I got above (minus parsing):

```
1: curl -o /dev/null https://www.dov.vlaanderen.be/geoserver/wfs?version=1.1.0&request=GetCapabilities
            Mean        Std.Dev.    Min         Median      Max
real        2.361       0.199       2.099       2.295       2.830       
user        0.139       0.017       0.111       0.140       0.168       
sys         0.148       0.019       0.110       0.148       0.178


1: curl -o /dev/null https://www.dov.vlaanderen.be/geoserver/dov-pub/wfs?version=1.1.0&request=GetCapabilities
            Mean        Std.Dev.    Min         Median      Max
real        0.516       0.228       0.356       0.456       1.467       
user        0.022       0.007       0.011       0.022       0.041       
sys         0.013       0.005       0.005       0.013       0.023


1: curl -o /dev/null https://www.dov.vlaanderen.be/geoserver/dov-pub/Boringen/wfs?version=1.1.0&request=GetCapabilities
            Mean        Std.Dev.    Min         Median      Max
real        3.852       0.452       2.660       3.971       4.394       
user        0.018       0.007       0.006       0.017       0.033       
sys         0.011       0.006       0.000       0.010       0.022
```

Here you can clearly see the influence of the document size in the result, the larger it is, the more time it takes to complete.

This leads me to my initial conclusion that the workspace-level endpoint is the best option, as this is the best trade-off between server-side rendering time and document size.

Would it be OK to switch to this endpoint (regarding Geoserver load)?

**Comment by Roel** [comment]
I'm going forward with this and prepare a PR to switch to workspace-level endpoints.

When issues arise during testing we can always easily revert or adjust.
