### ISSUE TITLE
Data korrelvolumemassa, volumemassa and watergehalte

### ISSUE THREAD

**Issue by sweco-beriac** [DOV-Vlaanderen/pydov#285]
* PyDOV version: last version
* Python version: 3.7.6 (jupyter notebook server 6.0.3
* Operating System: Windows 10

### Description

Hello,
I'm trying to get the data of korrelvolumemassa, volumemassa and watergehalte from the grondmonsters, but it comes always NaN, while in DOV really values exists.

### What I Did

import pydov
from pydov.util.location import Intersects, Box
  
#grondmonsters'
from pydov.search.grondmonster import GrondmonsterSearch
Grondmonster = GrondmonsterSearch()
fields = Grondmonster.get_fields()

#Volumemassa_watergehalte
df13 = Grondmonster.search(location=Intersects(Box(148750,213000, 153350, 215450,)),
return_fields=('boornummer','naam','korrelvolumemassa', 'volumemassa', 'watergehalte'))

print(df13)

             boornummer           naam  korrelvolumemassa  volumemassa  watergehalte
0    1445-GEO-17/047-B211  N003A                NaN          NaN           NaN
1    1445-GEO-17/047-B211   N002                NaN          NaN           NaN
2    1445-GEO-17/047-B211   N004                NaN          NaN           NaN
3    1445-GEO-17/047-B211  N003B                NaN          NaN           NaN
4    1445-GEO-17/047-B211  N003C                NaN          NaN           NaN
5            GEO-90/013-A      1                NaN          NaN           NaN
6            GEO-90/013-A      2                NaN          NaN           NaN
7            GEO-90/013-A      3                NaN          NaN           NaN
8            GEO-90/013-A      4                NaN          NaN           NaN
9            GEO-90/013-A      5                NaN          NaN           NaN
10           GEO-90/013-A      6                NaN          NaN           NaN
11           GEO-90/013-A      7                NaN          NaN           NaN
12           GEO-90/013-A      8                NaN          NaN           NaN
13           GEO-84/072-A      1                NaN          NaN           NaN
14           GEO-84/072-A      2                NaN          NaN           NaN
15           GEO-84/072-A      3                NaN          NaN           NaN
16           GEO-84/072-A      4                NaN          NaN           NaN
17           GEO-84/072-A      5                NaN          NaN           NaN
18           GEO-84/072-A      6                NaN          NaN           NaN
19           GEO-84/072-A      7                NaN          NaN           NaN
20           GEO-84/072-A      8                NaN          NaN           NaN
21          GEO-92/045-B7      1                NaN          NaN           NaN
22          GEO-92/045-B7      2                NaN          NaN           NaN
23          GEO-92/045-B7      3                NaN          NaN           NaN
24          GEO-92/045-B7      4                NaN          NaN           NaN
25          GEO-92/045-B7      5                NaN          NaN           NaN
26          GEO-94/052-B2     7A                NaN          NaN           NaN
27          GEO-94/052-B2     7B                NaN          NaN           NaN
28          GEO-94/052-B2     14                NaN          NaN           NaN
29          GEO-94/052-B2     19                NaN          NaN           NaN
..                    ...    ...                ...          ...           ...
```

Don't know what i'm doing wrong...
Thank you very much for your help.

Regards,
Beriac

**Comment by Roel** [comment]
Thanks for the report! This is a bug in pydov, we're using the wrong parameter in the Grondmonster type which results in the data not being found in the XML document.

We'll fix this soon and schedule a release. I'll also try to provide a workaround tonight.

**Comment by Roel** [comment]
You can work around the issue by defining a custom Grondmonster type with the correct XmlFields and registering this when instantiating the GrondmonsterSearch object:

```python
import pydov
#grondmonsters'
from pydov.search.grondmonster import GrondmonsterSearch
from pydov.types.fields import XmlField
from pydov.types.grondmonster import Grondmonster
from pydov.util.location import Box, Intersects


class GrondmonsterFixed(Grondmonster):

    fields = Grondmonster.extend_fields([
        XmlField(name='korrelvolumemassa',
                 source_xpath='/grondmonster/observatieData/observatie['
                              'parameter="KORRELVOLUMEMASSA"]/waarde_numeriek',
                 definition='',
                 datatype='float'),
        XmlField(name='volumemassa',
                 source_xpath='/grondmonster/observatieData/observatie['
                              'parameter="VOLUMEMASSA"]/waarde_numeriek',
                 definition='',
                 datatype='float'),
        XmlField(name='watergehalte',
                 source_xpath='/grondmonster/observatieData/observatie['
                              'parameter="WATERGEHALTE"]/waarde_numeriek',
                 definition='',
                 datatype='float')
    ])


Grondmonster = GrondmonsterSearch(objecttype=GrondmonsterFixed)
fields = Grondmonster.get_fields()

#Volumemassa_watergehalte
df13 = Grondmonster.search(location=Intersects(Box(148750,213000, 153350, 215450,)),
return_fields=('boornummer','naam','korrelvolumemassa', 'volumemassa', 'watergehalte'))

print(df13)
```

```
               boornummer   naam  korrelvolumemassa  volumemassa  watergehalte
0    1445-GEO-17/047-B211  N003A               2.65        1.627          57.7
1    1445-GEO-17/047-B211   N002               2.65        1.538          82.7
2    1445-GEO-17/047-B211   N004               2.65        1.986          25.4
3    1445-GEO-17/047-B211  N003B                NaN          NaN           NaN
4    1445-GEO-17/047-B211  N003C               2.65        1.365          69.8
```

This should allow you to proceed while we prepare a new release. Note that you can add extra fields that are not included by default in the same way.

**Comment by sweco-beriac** [comment]
Thank you very much Roel!
