### ISSUE TITLE
Mechanical tests

### ISSUE THREAD

**Issue by sweco-beriac** [DOV-Vlaanderen/pydov#287]
* PyDOV version: 2.0
* Python version: 3.8.3
* Operating System: Windows 10

### Description

I'm trying to retrieve which mechanical tests were carried out.
At this moment i can only retrieve if a mechanical test was carried out or not. 
I'm not sure how we can get the type of test or if its even possible.
for example: retrieve that "samendrukkingsproef" was carried out in that boresample.
Is there a way to retrieve this?

### Python code
from pydov.search.grondmonster import GrondmonsterSearch
grondmonster = GrondmonsterSearch()
fields = grondmonster.get_fields()
from pydov.util.location import Within, Box

df = grondmonster.search(location=Within(Box(122000, 187000, 124000, 189000)),
return_fields=('boornummer','naam','x','y','mechanisch'))
print(df)

Thank you very much.
King regards,
Beriac

**Comment by pjhaest** [comment]
Hi Beriac,  
The type of test is given in the _methode_ field.  The output is a flattened dataframe. So for every record the related _methode_ of measurement is given (or not). Not only the mechanical tests. The example below yields all the methods that are given for soil samples within the bounding box and where data from a mechanical test are available, amongst other measurements.  
As far as I know, there is no definition of possible values for the _methode_ field (@jorissynaeve ?). You would have to verify yourself in the list with all the available methods.  
```
from pydov.search.grondmonster import GrondmonsterSearch
from owslib.fes import PropertyIsEqualTo
gm = GrondmonsterSearch()
query = PropertyIsEqualTo(propertyname='mechanisch', literal='True')
df_gm = gm.search(location=Within(Box(122000, 187000, 124000, 189000)), query=query, return_fields=('boornummer','naam','x','y','methode'))
tests = df_gm.loc[df_gm.methode.notnull(), 'methode'].unique()
```   
Hope this clarifies things?

**Comment by Roel** [comment]
Pieter Jan, you're refering to the 'methode' field of the Korrelverdeling subtype. If I'm not mistaken (no domain expert here..) this is the method used to determine this result of the korrelverdeling (i.e. zeefproef or areometer). I think this is not what Beriac is looking for?

Beriac, I think what you need is in the 'proefuitvoeringsData' section in the XML:
```xml
<proefuitvoeringsData>
    <proefuitvoering>
        <proefnaam>OKP-ALGEMEEN</proefnaam>
        <uitvoerder>
            <naam>onbekend</naam>
        </uitvoerder>
        <identificatie>GEO-72/045</identificatie>
        <bedrijf_dienst>
            <naam>MVG - Afdeling Geotechniek</naam>
        </bedrijf_dienst>
    </proefuitvoering>
</proefuitvoeringsData>
```

You can make this section available in pydov by defining your own subtype for this, like described in the documentation [here](https://pydov.readthedocs.io/en/stable/output_fields.html#defining-custom-object-types), and further down [here](https://pydov.readthedocs.io/en/stable/output_fields.html#adding-a-new-subtype-to-a-main-type).

When instantiating a GrondmonsterSearch instance, you can then pass your own subclassed type with the 'proefuitvoering' fields instead of the 'korrelverdeling' fields:

```python
from owslib.fes import PropertyIsEqualTo

from pydov.search.grondmonster import GrondmonsterSearch
from pydov.types.abstract import AbstractDovSubType
from pydov.types.fields import XmlField, XsdType
from pydov.types.grondmonster import Grondmonster
from pydov.util.location import Box, Within


class Proefuitvoering(AbstractDovSubType):
    rootpath = './/grondmonster/proefuitvoeringsData/' \
        'proefuitvoering'

    fields = [
        XmlField(
            name='proef_naam',
            source_xpath='/proefnaam',
            definition='Naam van de verzameling van één of meerdere '
            'parameters',
            datatype='string',
            xsd_type=XsdType(
                'https://www.dov.vlaanderen.be/xdov/schema/latest/xsd/kern/grondmonster/GrondmonsterDataCodes.xsd',
                'ProefNaamEnumType')),
        XmlField(
            name='proef_uitvoerder',
            source_xpath='/uitvoerder/naam',
            datatype='string',
            definition='uitvoerder (firma) van de proef'),
        XmlField(
            name='proef_identificatie',
            source_xpath='/identificatie',
            datatype='string',
            definition='Identificatie id of nummer van de referentie'),
        XmlField(
            name='proef_bedrijf_dienst',
            source_xpath='/bedrijf_dienst/naam',
            datatype='string',
            definition='bedrijf of dienst waarvoor de referentie kan gevonden worden')]


class GrondmonsterProefuitvoering(Grondmonster):
    subtypes = [Proefuitvoering]


grondmonster = GrondmonsterSearch(objecttype=GrondmonsterProefuitvoering)

df = grondmonster.search(
    location=Within(Box(122000, 187000, 124000, 189000)),
    query=PropertyIsEqualTo('mechanisch', 'True'),
    return_fields=('boornummer', 'naam', 'x', 'y', 'proef_naam', 'proef_identificatie', 'proef_bedrijf_dienst'))

print(df[df.proef_naam == 'SAMENDRUKKING'])
```

Since the subtype fields originate from the XML document they cannot be used in a search query, contrary to the 'mechanisch' field which is a WFS aggregate. The most efficient way is to use the latter in the query parameter and subsequently filter the resulting dataframe further to keep only the results you're after.

**Comment by pjhaest** [comment]
Good point Roel. I should have checked the source code before answering.  
Indeed, _methode_ is only defined for the subtype  [Korrelverdeling](https://github.com/DOV-Vlaanderen/pydov/blob/master/pydov/types/grondmonster.py). I don't know when we decided on this, but it seems confusing, at least for me, to have a default field _methode_ that is only valid for one test. I would suggest to include all tests during the next code sprint? E.g. _proef_naam_ above would also become _methode_. Or am I missing something more?

**Comment by sweco-beriac** [comment]
Thank you Roel and pjhaest.
Thats exactly what i was trying to achieve.
i was working on something similar. but your solution is better than mine :)

            XmlField(name='samendrukking',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="SAMENDRUKKING"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Schuifweerstand generiek',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="SCHUIFWEERSTAND_GEN"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Schuifweerstand CD',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="SCHUIFWEERSTAND_CD"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Schuifweerstand CU',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="SCHUIFWEERSTAND_CU"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Schuifweerstand UU',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="SCHUIFWEERSTAND_UU"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Doorlatendheid CV',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="DOORLATENDHEID_CV"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Doorlatendheid VVH',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="DOORLATENDHEID_VVH"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Doorlatendheid VVV',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="DOORLATENDHEID_VVV"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Doorlatendheid GEN',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="DOORLATENDHEID_GEN"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Standaard proctorproef',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="PROCTOR"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Versterkte proctorproef',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="PROCTOR_VERSTERKT"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Meest losse pakking',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="LOSSE_PAKKING"]/',
                 definition='',
                 datatype='string'),
            XmlField(name='Vinproef',
                 source_xpath='/grondmonster/proefuitvoeringsData/proefuitvoering['
                              'proefnaam="VINPROEF"]/',
                 definition='',
                 datatype='string'),
        ])

Regards,
Beriac

**Comment by Roel** [comment]
I'm going to close this issue since I believe this is solved? Don't hesitate to reopen if it is not the case or open a new issue if you have further questions!
