### ISSUE TITLE
boreholes: height of topography 'zero' and not empty in extraction data

### ISSUE THREAD

**Issue by denilka** [DOV-Vlaanderen/pydov#288]
### Description

Seen during data evaluation of H3O-De Voorkempen: Extraction of boreholes with no information about the topography, extracts as '0' value which results in wrong perception of '0mTAW' for users. But in fact, the information must be empty for mv_mtaw value, because not known and not filled out in DOV. Examples in attachment, colomn AD.
### What I Did

[pyDOVBorehole.xlsx](https://github.com/DOV-Vlaanderen/pydov/files/5378351/pyDOVBorehole.xlsx)

**Comment by Roel** [comment]
Hey Katrien!

Can you maybe share how you got the Excel file (i.e. what code was used to generate it)?

I cannot reproduce the issue in current pydov on my machine:
```python
from owslib.fes import PropertyIsEqualTo
from pydov.search.boring import BoringSearch

bs = BoringSearch()

df = bs.search(
    query=PropertyIsEqualTo(
        'pkey_boring',
        'https://www.dov.vlaanderen.be/data/boring/1969-092720')
)

print(df)
```
```
[000/001] c
                                         pkey_boring       boornummer         x         y  mv_mtaw  start_boring_mtaw  gemeente  diepte_boring_van  diepte_boring_tot datum_aanvang                          uitvoerder  boorgatmeting  diepte_methode_van  diepte_methode_tot  boormethode
0  https://www.dov.vlaanderen.be/data/boring/1969...  GEO-68/465-b122  161833.0  221375.0      NaN              16.41       NaN                0.0               11.0    1969-05-30  Rijksinstituut voor Grondmechanica          False                 0.0                 2.2  lepelboring
1  https://www.dov.vlaanderen.be/data/boring/1969...  GEO-68/465-b122  161833.0  221375.0      NaN              16.41       NaN                0.0               11.0    1969-05-30  Rijksinstituut voor Grondmechanica          False                 2.2                11.0   pulsboring
```

As you can see in the output, mv_mtaw is listed as `NaN` here, which is different from 0 (as f.ex. in diepte_boring_van).

**Comment by katrijndirix** [comment]
Hey Roel,

It was I who generated the excel, and I just noticed that indeed the pydov export is correct. The issue arose during a subsequent step in my code, where I clipped the pydov-output using a polygon shapefile, prior to exporting the excel. That step apparently set the NaN fields to 0.

My apologies and thank you for the swift reply,
Katrijn

**Comment by pjhaest** [comment]
Ok, good to hear that pydov works just fine :-)
