### ISSUE TITLE
Missing fields in Sondering and documentation (mv_mtaw and sondeernummer)

### ISSUE THREAD

**Issue by ChandraAlgoe** [DOV-Vlaanderen/pydov#289]
The return field ‘mv_mtaw’ does not exist for CPT
The return field ‘sondeernummer’ exists but isn't mentioned in the documentation

**Comment by pjhaest** [comment]
Thx for the heads-up. 'sondeernummer ' will be added to the documentation in the next release.
Regarding 'mv_mtaw': this field should be added to the type definition in the next code sprint

**Comment by Roel** [comment]
I believe `mv_mtaw` is the field `/sondering/sondeerpositie/oorspronkelijk_maaiveld/waarde` in the XML, similar to where it is in Boring. We can add this in the next version.
