### ISSUE TITLE
Query on self-added parameters in subtypes 

### ISSUE THREAD

**Issue by binomaiheu** [DOV-Vlaanderen/pydov#295]
* PyDOV version: 2.0.0
* Python version: 3.8.3
* Operating System: MS Windows 10

### Description

First of all, thanks a lot for the nice library ! I was trying to construct a custom query to lookup groundwater wells with specific inner diameters in the DOV dataset. Looking at the XML of a 'filterfiche', I believe in the XML this should be under :
```
<filter>
  <opbouw>
    <onderdeel>
        <binnendiameter>
```
So, after going through the manual, I assume I have to create a new subtype in a daughter class of "GrondwaterFilter". I added 2 fields, however the "search" method of GrondwaterFilter Search doesn't let me query on the newly created fieldname. I pasted my code below. Probably doing something stupid, or this question may have been asked already, but I'm fairly new to pydov, so apologies is this is the case. 

### What I Did

Code below here to illustrate

```python
from owslib.fes import PropertyIsBetween

from pydov.search.grondwaterfilter import GrondwaterFilterSearch
from pydov.types.grondwaterfilter import GrondwaterFilter
from pydov.types.fields import XmlField
from pydov.util.location import WithinDistance, Point

from pydov.types.abstract import AbstractDovSubType


search_radius = WithinDistance(
    Point(x0, y0),
    20000.,
    distance_unit="meter"
    )

class FilterOnderdeel(AbstractDovSubType):
    
    rootpath = './/filter/opbouw/onderdeel'

    fields = [
        XmlField(name='filter_binnen_diameter',
                 source_xpath='/binnendiameter',
                 datatype='float'),
        XmlField(name='filter_element',
                 source_xpath='/filterelement',
                 datatype='string')
    ]

class MyFilter(GrondwaterFilter):
    subtypes = [FilterOnderdeel]
    
fs = GrondwaterFilterSearch(objecttype=MyFilter)
df = fs.search(query=PropertyIsBetween('filter_binnen_diameter', 30., 60. ), 
               location=search_radius)
```

This yields a 

```
  File "C:\Work\Analysis\pydov_query_gwfilter_subtype.py", line 41, in <module>
    df = fs.search(query=PropertyIsBetween('filter_binnen_diameter', 30., 60. ),

  File "C:\Tools\anaconda3\lib\site-packages\pydov\search\grondwaterfilter.py", line 145, in search
    self._pre_search_validation(location, query, sort_by, return_fields,

  File "C:\Tools\anaconda3\lib\site-packages\pydov\search\abstract.py", line 465, in _pre_search_validation
    raise InvalidFieldError(

InvalidFieldError: Cannot use return field 'filter_binnen_diameter' in query.
```

So it seems it does not let me query on the parameter I added. When i do a 'get_fields()' however, it does list the newly added fields in the output, so I'm guessing they should be in there. 

``` python
In[21]: fs.get_fields()['filter_binnen_diameter']
Out[21]: 
{'name': 'filter_binnen_diameter',
 'type': 'float',
 'definition': '',
 'notnull': False,
 'query': False,
 'cost': 10}
``` 

Could be that the querying is restricted to the fields available in the wfs ? Or should it not matter ? It's not a real problem, I can always subset after I have retrieved the full dataframe, but I seemed to be getting a lot of duplicates when i did a naive query of  just adding them to the main type as such : 

```python
class MyFilter(GrondwaterFilter):
   fields = GrondwaterFilter.extend_fields([
        XmlField(name='filter_binnen_diameter',
                 source_xpath='/filter/opbouw/onderdeel/binnendiameter',
                 datatype='float'),
        XmlField(name='filter_element',
                 source_xpath='/filter/opbouw/onderdeel/filterelement',
                 datatype='string')
    ])


q = PropertyIsBetween(propertyname='filter_binnen_diameter', lower='30', upper='60')

gw = GrondwaterFilterSearch(objecttype=MyFilter)
df = gw.search(query=q, location=iflux_search_radius)
```

so was trying to optimise the query a little to just get the info i wanted. Anyway, gratefull for any help or pointers you can give me (having about half a day of pydov experience for the moment :-)). 

Cheers,
Bino

**Comment by Roel** [comment]
Hi Bino!

Nice to see that even half a day is enough to get to the more advanced parts of the library ;)

> Could be that the querying is restricted to the fields available in the wfs ?

Your assumption is correct: pydov works by querying the WFS services, subsequently download the XML file for each result (when necessary) and combining both in a Pandas dataframe. We cannot query the XML service and as a result you can only use WFS fields in your query.

This is mentioned in the output of the `get_fields()` as `'query': False`:
```python
In[21]: fs.get_fields()['filter_binnen_diameter']
Out[21]: 
{'name': 'filter_binnen_diameter',
 'type': 'float',
 'definition': '',
 'notnull': False,
 'query': False,
 'cost': 10}
```

As for optimization, you can try limiting your results by another field that is available in the WFS, or use a finer spatial filter. For the XML fields, the only way is to get all the results and then subset/filter them afterwards.

**Comment by binomaiheu** [comment]
Hi Roel,
Ha, great, thanks for the reply, good to know that it's a design feature. I'll try indeed optimising by using other fields and filter the dataframe afterwards.
Thanks!
b.
