### ISSUE TITLE
Issues when XML is unavailable

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#297]
* PyDOV version: master
* Python version: 3.8
* Operating System: Ubuntu

### Description

When the XDOV server is unavailable and/or returns a 404 on an XML request we should:
* not store the result in our cache
* warn the user that their dataframe is incomplete
* possibly skip the remote XSD schema loading and issue a warning there too

This should allow users to:
* keep their older data in cache instead of it being overwritten by an error page
* know that their dataframe is not complete or up-to-date
* still use pydov for queries using only WFS fields and/or cached data

### What I Did

```python
from pydov.search.boring import BoringSearch

bs = BoringSearch()

df = bs.search(max_features=1)
print(df)
```

```
[000/001] .
                                         pkey_boring     boornummer        x         y  mv_mtaw  start_boring_mtaw          gemeente  diepte_boring_van  diepte_boring_tot  datum_aanvang uitvoerder  boorgatmeting  diepte_methode_van  diepte_methode_tot  boormethode
0  https://www.dov.vlaanderen.be/data/boring/2016...  kb29d84e-B574  92424.0  170752.0      NaN               40.0  Wortegem-Petegem                NaN                0.0            NaN   onbekend            NaN                 NaN                 NaN          NaN
```

```
> zcat /tmp/pydov/boring/2016-122561.xml.gz | head


<!-- THEME DEBUG -->
<!-- THEME HOOK: 'html' -->
<!-- FILE NAME SUGGESTIONS:
   * html--error--502.html.html.twig
   * html--error.html.twig
   x html.html.twig
-->
<!-- BEGIN OUTPUT from 'themes/dov_webuniversum/templates/html.html.twig' -->
```

**Comment by pjhaest** [comment]
I second this, just had the same issue, thinking it was had to do with the data or my code :-s
