### ISSUE TITLE
Voorbeeld XML file in repo

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#3]
As for the moment the XML service based on the URL is not yet provided, it would be useful to have an example file of the XML format in the repo. Hence, we can already provide and test the conversion functionality.

**Comment by johanvdw** [comment]
We will still make a minor adjustment to the export - I will publish the file as soon as this is done.

**Comment by johanvdw** [comment]
Even ter info: de geplande aanpassing is het toevoegen van de berekende diepte tov taw die nu niet in de xml export zit (enkel tov referentiepunt + een lijst referentiepunten).
