### ISSUE TITLE
CI failing in oefen - Geonetwork unreachable

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#327]
CI is failing since a few weeks (last successful run was on 4th of May), because Geonetwork in oefen is not online. Is this a known issue and if it is not, can someone from DOV take a look at this?

Thanks!

**Comment by debaetpa** [comment]
Geonetwork in oefen should now be available again.

**Comment by Roel** [comment]
Tests are working again, thanks!
