### ISSUE TITLE
Mogen niet-publieke data geraadpleegd worden met pydov?

### ISSUE THREAD

**Issue by yairlevy** [DOV-Vlaanderen/pydov#330]
* PyDOV version: 2.0.0
* Python version: 3.8.3
* Operating System: Windows 10

### Description

When querying for watersamples or screens, I understand only public data could be gathered using pydov's functionalities. Is it correct?

### What I Did

```
I used tutorial code from https://pydov.readthedocs.io/ to retrieve data.
```

**Comment by yairlevy** [comment]
Tinneke De Rouck informed me in a private mail that public data only indeed can be queried with pydov functionalities. May my inquiry be considered as a pledge to consider implementing password protected access to internal data using pydov.

During the february 2021 codesprint, it appeared many challenges stood in the way of such implementation. Hints,  advices or insights to solve or close the issue?

Thanks.

Best regards.

**Comment by pjhaest** [comment]
I think the question for the maintainers of DOV is whether pydov will be used as the main API for all users (access only to the xml exports of DOV), or if another API with similar functionalities will be provided on the data itself for priviliged users?

**Comment by Roel** [comment]
I'm going to close this issue, as it is the same as #298. We can continue the discussion in the other issue.
