### ISSUE TITLE
Provide documentation on data column origin

### ISSUE THREAD

**Issue by stijnvanhoey** [DOV-Vlaanderen/pydov#35]
Currently, the [data documentation](file:///home/stijn_vanhoey/githubs/dev_pydov/docs/_build/html/description_output_dataframes.html#boreholes) provides for each variable the DOV scheme origin. The source should be updated to the real used source (WFS or XML) to clarify the effort of data transfer for a given query

**Comment by Roel** [comment]
I started working on this and I'm in the process of preparing a pull request. Some questions popped up while trying to unify the dataframes between boreholes/interpretations and groundwater:
* In groundwater we have the 'gemeente' field which is currently lacking in boreholes/interpretations. I switched it from NIS code to 'human readable' names and suggest adding it to boreholes and interpretations as well. Ok?
* In groundwater we have the 'betrouwbaarheid' field which we explicitly did not include in the interpretations. Is the use different enough between the two to justify the difference in availability or do we align the output dataframes and thus add it to the interpretations or remove it from groundwater? Thoughts?

**Comment by pjhaest** [comment]
@Roel 
* Ok on the 'gemeente' attribute in the boreholes and interpretations
* If it's more generic: include the 'betrouwbaarheid' attribute in the interpretations as well. For now I don't think it's very useful, but maybe in the future it can be a more objective attribute.

**Comment by Roel** [comment]
Ok! I updated the dataframes accordingly.
See PR #38

**Comment by Roel** [comment]
Remark about 'gemeente': this field is not compulsary, so it can be `null`. This might lead to interesting results when using it as a search parameter..

F.ex a search for all boreholes where gemeente = `Wuustwezel` will not return all boreholes which are (based on their coordinates) located in Wuustwezel, since there might be records where this is the case but gemeente is `null`.

Should we add metadata about which fields are mandatory and which ones aren't, or do we leave out `gemeente` altogether?

**Comment by Roel** [comment]
I added the `gemeente` field and will make the cardinality (mandatory or not) of the fields available via the metadata.

**Comment by pjhaest** [comment]
Ok, but can't we make a background check with the coordinates and a vector file of all communities in the test folder or so? Everyone *should* read the metadata but you know these things go in practice.

**Comment by Roel** [comment]
We can look into providing such an example in the future, but for now I would stick to documenting.

**Comment by pjhaest** [comment]
agreed
