### ISSUE TITLE
Problem connecting to dov-server?

### ISSUE THREAD

**Issue by katrijndirix** [DOV-Vlaanderen/pydov#364]
* PyDOV version: 2.2.0
* Python version: 3.8
* Operating System: Windows

### Description

I tried collecting some simple grondwaterfilter data using GrondwaterFilterSearch(), but got an error back

### What I Did

GrondwaterFilterSearch().get_fields()

Error message:
  File "C:\Users\DIRIXK\.conda\envs\pygeo_38\lib\site-packages\pydov\util\owsutil.py", line 157, in get_featurecatalogue_uuid
    len(md_metadata.contentinfo) > 0 else None
AttributeError: 'NoneType' object has no attribute 'contentinfo'

I also checked for Boringsearch().get_fields() and it throws the same error, so I guess something goes wrong when connecting to the server?

**Comment by katrijndirix** [comment]
Update: as of this morning (20/10/2022), things are working again as normal.

**Comment by debaetpa** [comment]
it turned out the dov geonetwork instance was offline.
