### ISSUE TITLE
Update name and description

### ISSUE THREAD

**Issue by peterdesmet** [DOV-Vlaanderen/pydov#4]
I would call this package:

> pydov

It's shorter than `dov-pydownloader`, sounds more official (only one pydov package) and easily applicable to R: `rdov`.

I would also update the description to:

> A python package to retrieve data from Databank Ondergrond Vlaanderen (DOV)

Rather than "A python package to extract data from the DOV web application", as you don't really extract data from the application, but from the webservices. Also `retrieve` implies more of a request/response than `extract`.

**Comment by johanvdw** [comment]
+1 . The name is more generic. This is useful should we add non-downloading capabilities (minimal processing/plotting/... ).

**Comment by pjhaest** [comment]
I agree, keep it short

**Comment by stijnvanhoey** [comment]
good idea, name and description updated
