### ISSUE TITLE
Support polygons as location parameter

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#56]
It should be possible to provide a polygon as location parameter of the search method. (next to bbox)

**Comment by Roel** [comment]
Progress can be tracked in the `location-filters` branch.

**Comment by TimFranken** [comment]
@Roel . What is the progress or timeline for implementation of this feature? This would be something I could use in the very near feature. Happy to contribute to it myself in case needed.

**Comment by Roel** [comment]
We have yet to start implementing the polygon feature. I was still thinking about how to do it, so input is certainly welcome at this point.

My first thought would be to start simple (and without adding dependencies) and support polygons based on WKT strings. Would that work for your use case?

**Comment by TimFranken** [comment]
I'd prefer GeoJson since they are easier to generate and work with. Additional dependencies in that case could be limited to the json library itself. I might implement a Polygon class in the location.py in the forked repo that takes a geojson as input and outputs the gml representation since that would work for my use case. Alternative would be to use the ogr library but I'm guessing that would mean too much additional dependencies?

**Comment by stijnvanhoey** [comment]
I do agree on the usage of geojson as an input for the user would be convenient. Notice that [shapely](https://shapely.readthedocs.io/en/latest/) provides [support](https://gist.github.com/drmalex07/5a54fc4f1db06a66679e) for conversion to/from wkt but this would bring in too much dependencies in as well. Taking that into account, I do think WKT or geojson are both valid options, it will be a matter of providing documentation to the user on how to transform different formats to the required format for pydov.

**Comment by Roel** [comment]
GeoJSON would be great! I thought about using ogr too, but would prefer not to add that dependency at this point. If we would be able to support this with only the (built-in) `json` module this would be perfect.

I looked into `shapely` as well, but I think it does not support conversion to GML (what we need for the WFS GetFeature filter). We need to tranform either GeoJSON and/or WKT into GML, not the one into the other.

@TimFranken The `location-filters` branch would indeed be the starting point if you would want to implement this. It currently lacks docstring and tests though, I will try to add at least the first in the next couple of days.

**Comment by pjhaest** [comment]
Nice to see the development of this feature!
I think it's good to provide enough flexibility to the user for the pre- and postprocessing. So you could indeed leave the creation of the GML up to the user (with an example method in the docs!), not requiring a certain package for the conversion itself (ogr, geopandas etc.). In addition, I would not mind too much about complex geometries to start with. Currently, I don't see a use-case with inner rings for the query of DOV. And if so, it could/should be part of the post-processing?
