### ISSUE TITLE
XML parsing from downloaded file

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#62]
The current code for interpretations is applicable for xml parsing from the webservice. 
Later on, we should verify which adjustments are necessary to parse downloaded xml files where 'boringen' and 'interpretations' can both be present (currently, the type does not define the full rooth path in the xml of  mixed data)

**Comment by stijnvanhoey** [comment]
As discussed today, this is considered out of scope of the package... closing here.
