### ISSUE TITLE
notebooks and tutorials: integrate examples into the docs folder

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#66]
shouldn't we put the notebooks and eventual other tutorials under 'examples' instead of 'docs'? Or create a new map 'tutorials'. 
The current position under 'docs' is somewhat full with other rst's etc.

**Comment by stijnvanhoey** [comment]
By having them in the docs, we can integrate the notebooks with sphinx documentation website using the [nbsphinx](https://nbsphinx.readthedocs.io/en/0.3.3/) package, making them appear as webpages within the documentation.

**Comment by stijnvanhoey** [comment]
Still, we can put them in a folder `docs/notebooks` to have them celarly separated from the `rst` files and still integrate it into the sphinx documentation website.

**Comment by pjhaest** [comment]
Ok, it's already implemented like that. However, a bit confusing with a folder 'examples' next to docs

**Comment by stijnvanhoey** [comment]
OK, let's focus this issue on the removal of the 'example' directory and integration of the examples in the   documentation website (i.e. `docs`) folder

**Comment by pjhaest** [comment]
@Roel is it ok if 'examples' is deleted? The examples in boring_search.py are all (or almost) included in the notebook example already provided.
I would suggest not to provide example scripts, only code in notebooks, with the necessary comments and output. Since it is not the intention to go beyond the supply of the data, which is already coded in pydov.

**Comment by Roel** [comment]
Ok with me to replace the example scripts with notebooks!

**Comment by Roel** [comment]
@stijnvanhoey Do you have experience integrating the notebooks with nbsphinx? It works on my machine after installing pandoc with its installer (pandoc package itself was not enough), but I can't get it to work on Travis (and haven't even tried on ReadTheDocs).

My (to date, failed) attempts can be found in the sphinx-notebook branch: https://github.com/DOV-Vlaanderen/pydov/tree/sphinx-notebooks

**Comment by stijnvanhoey** [comment]
We did it for [niche vlaanderen](https://github.com/inbo/niche_vlaanderen), I'll have a look at it.

**Comment by johanvdw** [comment]
I can help as well, though I have not used it together with pandoc.

**Comment by stijnvanhoey** [comment]
With respect to the travis build errors, the issue apparently was the fact that the environmentl variables were not available inside the tox-environments...[ adding](https://github.com/DOV-Vlaanderen/pydov/blob/sphinx-notebooks/tox.ini#L17) the `passenv` option to the tox.ini file seems to fix this issue, as the HOME var is available inside the tox env.

[Still a lot of red WARNINGS ](https://travis-ci.org/DOV-Vlaanderen/pydov/jobs/393282552) in the sphinx build, we have a build ;-)
![image](https://user-images.githubusercontent.com/754862/41507524-11250552-7234-11e8-89bc-db93ec2395ac.png)

**Comment by Roel** [comment]
I have added you to the readthedocs account!

**Comment by stijnvanhoey** [comment]
It works, but we still have to figure out the handling of notebooks during build and documentation. Currently, the notebok rerun is set on 'never' (althoudgh docs say something differently, hm) to make sure 
we get RTD working. Might need further alteration or change docs ;-)

**Comment by stijnvanhoey** [comment]
Closing the issue, notebooks are collected in the `tutorials` section and notebooks are not rerun during build procedure by default.
