### ISSUE TITLE
XML string parsing error

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#69]
XML can contain non-ascii that fail upon encoding (see below).
For example: "u'SocietÃ© Belge des BÃ©tons'"
Check boring type and search for 
{'start_boring_mtaw': 61.0, 'boorgatmeting': '{UNRESOLVED}', 'uitvoerder': '{UNRESOLVED}', 'boornummer': 'kb34d93e-B183', 'pkey_boring': 'https://www.dov.vlaanderen.be/data/boring/1928-031159', 'mv_mtaw': '{UNRESOLVED}', 'diepte_boring_van': '{UNRESOLVED}', 'y': 177156.1, 'x': 234685.7, 'datum_aanvang': datetime.date(1928, 1, 2), 'diepte_boring_tot': 15.0, 'gemeente': 'Bilzen'}
```
File "D:\_wd\pydov\types\abstract.py", line 59, in typeconvert
    return str(x).strip()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-7: ordinal not in range(128)
```

**Comment by pjhaest** [comment]
Ok, had a quick look and following encoding to "utf-8" would do the trick. 

pydov/types/abstract.py, lines 57 etc.
```
        if returntype == 'string':
            def typeconvert(x):
                return str(x.encode("utf-8") ).strip()
```
I took the liberty to already put this in master, please undo if I overlooked conflicts

**Comment by Roel** [comment]
Please don't push directly to master but create a PR instead, so we can ensure the tests still pass before merging to master. Thanks :)

Your suggestion might do the trick, but encoding is one of the things that vary between Python 2 and 3, so needs to be doublechecked in different versions.

**Comment by pjhaest** [comment]
Sorry for that, will do

**Comment by pjhaest** [comment]
confirming that it works in Python 2.7 and 3.6.
