### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#72]
Do we allow for use cases in this repo?
If so, where to put them: in the docs or some other folder?

**Comment by stijnvanhoey** [comment]
I would propose to create a separate repo in the DOV-Vlaanderen organisation:
- it provides flexibility (use cases doe not need to pass all the strict unit-testing,...)
- it prevents the users from downloading the complete package and the use cases, but they can install the package and download the use case repo
- We can use the power of [binder](https://mybinder.org/) to let users start/test/try the use cases online

**Comment by pjhaest** [comment]
Fine by me. I also think pydov should be as 'lightweight' as possible

**Comment by Roel** [comment]
Ok, sounds good to me!

**Comment by stijnvanhoey** [comment]
naming?

* `pydov-usecases`
* `pydov-use-cases`
* `pydov-applications`

**Comment by johanvdw** [comment]
We could also have a list in our documentation pointing towards projects
and use cases using pydov.
Especially if it is an one time example (not maintained by the team) I
would host under your own account.

**Comment by stijnvanhoey** [comment]
Good point about the external sources hosted under your own account (maintained by yourself) instead of trying to have a separate dov repo without real maintainer on the individual cases once added. Closing this issue, agreeing referring to external cases by just linking to them in de doc pages.
