### ISSUE TITLE
example notebooks - using latest pydov version

### ISSUE THREAD

**Issue by johanvdw** [DOV-Vlaanderen/pydov#76]
Just a small comment:
In the notebooks you do
```
# Insert current tree in the sys path to be able to import local copy of 'pydov'
sys.path.insert(0, '../../')
```
You can also use editable (develop) mode to install:
```
pip install -e 
```
That way you are sure you always use the current version, without having to edit your path.

**Comment by stijnvanhoey** [comment]
Fixed
