### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#77]
A newbie question: I stumbled across the 'good practices' of pytest where /src/pydov is advised, next to /tests/ to overcome problems using virtual environments with tox. See https://docs.pytest.org/en/latest/goodpractices.html 
But the current setup seems to work fine?

**Comment by pjhaest** [comment]
this seems to be an active discussion https://github.com/pypa/python-packaging-user-guide/issues/320

**Comment by stijnvanhoey** [comment]
As far as I understand, this is mainly important if we have a test-folder with  subdirectories containing the same files/names, which we don't have. Although the arguments described in the [blogpost](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure) do make sense...

**Comment by pjhaest** [comment]
Discussed in august code sprint: keep testing locally as simple as possible with current structure
