### ISSUE TITLE
Add coordinates to interpretations

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#88]
During the august code sprint it became apparent that uses not always need 'boring' data next to interpretations. If only interpretations are searched, the users need access to the coordinates as well. 
This can be circumvented by adding the wfs fields to the 'return_fields' argument but the column name then differs. Therefore, it is best to add these wfs data to the dataframe for all possible queries.

**Comment by Roel** [comment]
This should be fixed in 9187ae4c2fb2b858d0fcb23464439516fa92ec83
