### ISSUE TITLE
correct gebruik namespaces

### ISSUE THREAD

**Issue by johanvdw** [DOV-Vlaanderen/pydov#9]
Momenteel gebruiken we de in de xml gebruikte afkorting van de namespace hardcoded. We zouden beter de namespaces zelf mappen, eventueel naar None, zodat het ook correct werkt met andere XML files die ook aan het schema voldoet.

https://github.com/martinblech/xmltodict#namespace-support

**Comment by pjhaest** [comment]
+1 
Kun je een voorbeeld geven?
