### ISSUE TITLE
AppVeyor build failing

### ISSUE THREAD

**Issue by Roel** [DOV-Vlaanderen/pydov#94]
The AppVeyor build is currently failing because it only installs requirements_dev.txt, and that does not include the `-r requirements` anymore.

Shall I install the requirements.txt in AppVeyor manually too or do we add the (contents of) requirements.txt to requirements_dev as before?

**Comment by stijnvanhoey** [comment]
We can add the contents of requirements.txt into requirements_dev again, this shouldn't be a problem.
