### ISSUE TITLE
Internal links in README broken

### ISSUE THREAD

**Issue by pjhaest** [DOV-Vlaanderen/pydov#97]
I noticed that the internal links on the README are broken?

**Comment by stijnvanhoey** [comment]
Indeed. This is due to the integration of the Readme.rst file inside the sphinx docs and using the relative links of sphinx documents. I'll adapt he readme and mek sure the github readme is showing full links.

**Comment by Roel** [comment]
I think this can be closed, since mering #119 ?

**Comment by pjhaest** [comment]
Indeed, closing
